apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-ex-vjh3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-ex-vjh3
    app.kubernetes.io/part-of: pytest-port
  name: python-ex-vjh3
  namespace: johnmcollier-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-ex-vjh3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-ex-vjh3
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:32b8835b0ff3adbf5b62b2242c8805ad6e213d7ae6e279acf2350b80b94fcc4b
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
